### ISSUE TITLE
Entry ekleme kutusuna bkz url butonları ekleme

### ISSUE THREAD

**Issue by metinorak** [metinorak/yordep#12]

**Comment by fatihcirakk** [comment]
url ve bakınız botonu olmalı diye düşünüyorum yorum yazma kısmında, koda baktıgımda tüm entry içinde 
"bkz:" aranıyor, eger ciddi bir kulllanıcı sayısı olursa sscriptin çalıştıgı web serverin. on the fly bunu yapmak ne kadar performansı düşürür bilemiyorum

**Comment by metinorak** [comment]
bunun butonla ilgisi yok da performans kaybı olduğu doğrudur. hatta çok fena etkisi olur. bu, entry girilirken bkzlar linke çevrilip veritabanına atılarak da çözülebilir. o zaman da eski entrylere bkz eklendiğinde aktif olmayacaktır. ama bana bu da doğru bir çözüm gibi gelmedi.

**Comment by fatihcirakk** [comment]
anlıyorum bende bazı güzel php fonksiyonları gördüm text içinde "url" detect edip linke çeviren ancak performansı düşürdügü için çok tercih edilmiyor diye okudum, 

bunun yerine comment girilen yere bir de opsiyonel link kutusu koysak sence olurmu ? yada sozluklerdeki gibi url butonu ve bkz butonu olablir yorum yazılan kutunun üstünde ?

**Comment by metinorak** [comment]
olabilir ama kullanıcı belki bkzyi elle eklemiştir. bu özelliği kullanabilmek için mutlaka bunların text içinde aranması gerekiyor. yani entry okunurken değil de en azından entry girilirken bunun yapılması lazım.

**Comment by fatihcirakk** [comment]
$template = "/(http|https|ftp|ftps):\/\/[a-zA-Z0-9-.]+(.|\/)[a-zA-Z]{1,}(\/\S*)?/";
$last_change= preg_replace($template, '<a  href="$0" rel="nofollow">$0</a>', $last_change);
	
$template = "/(^|\A|\s)((www\.)[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,4}(\/\S*)?)/";
$last_change= preg_replace($template, '<a  href="https://$0" rel="nofollow">$0</a>', $last_change);

function add_bkz_url içerisine yukardaki satırları ekleyince hyperlink(URL) leri anlayabiliyor ve hyperlink haline getiriyor. 


https://www.google.com/
www.youtube.com 

bunlarla düzgün çalıştı.

**Comment by fatihcirakk** [comment]
$template = "/(http|https|ftp|ftps):\/\/[a-zA-Z0-9-.]+(.|\/)[a-zA-Z]{1,}(\/\S*)?/";
	$last_change= preg_replace($template, '<a style="color:#80C14B" href="$0" rel="nofollow">$0</a>', $last_change);

**Comment by fatihcirakk** [comment]
http://www.google.com/
https://www.google.com/.
www.google.com
www.google.com.
www.google.com/test
google.com
google.com,
google.com/test
123.com/test
www.123.com.au
ex-ample.com
http://ex-ample.com
http://ex-ample.com/test-url_chars.php?param1=val1.
http://ex-ample.com/test-url_chars?param1=value1&param2=

**Comment by fatihcirakk** [comment]
edit: 

 $template = '@(http)?(s)?(://)?(([a-zA-Z])([-\w]+\.)+([^\s\.]+[^\s]*)+[^,.\s])@';
        $last_change = preg_replace($template, '<a style="color:blue;font-size:18px" href="http$2://$4" target="_blank" title="$0">$0</a>', $last_change);


bu kod "add_bkz_url " içine eklenince tüm url'leri detect ediyor. 
tüm linkler için çalışıyor

**Comment by fatihcirakk** [comment]
` $template = '@(http)?(s)?(://)?(([a-zA-Z])([-\w]+\.)+([^\s\.]+[^\s]*)+[^,.\s])@';
 $last_change = preg_replace($template, '<a style="color:blue;font-size:18px" href="http$2://$4" target="_blank" title="$0">$0</a>', $last_change);`
