### ISSUE TITLE
açılan başlıgı sildigimde sol frameden başlık o anda yok olmuyor ve tıklayınca aşagıdaki hata geliyor.

### ISSUE THREAD

**Issue by fatihcirakk** [metinorak/yordep#33]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-10,0' at line 1

sildikten sonra sol frame'de o başlıga tıklayınca böyle bir başlık bulunamadı hatası daha mantıklı olur.

**Comment by fatihcirakk** [comment]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-10,0' at line 1

problem devam ediyor, sildigim başlık sol framede duruyorken tıklarsam bu hata geliyor, ayrıca sildigim başlıga o anda yorum girebiliyorum ayrı bir hata bu da

**Comment by metinorak** [comment]
eski hatadan kalma başlıklar. yeni başlık açıp sildiğinde listede gözükmediğini göreceksin. o başlıkları veritabanından kaldırabilirsin.

**Comment by metinorak** [comment]
puanlamayı opsiyonel yaptıktan sonra ortaya çıkan sorunlar bunlar. yamalı bohça gibi bir script olduğu için geliştirilmesi kolay olmuyor.

**Comment by fatihcirakk** [comment]
aynen bende farkettim, eski başlıklarda oluyor, yeni deneyince oluşmadı, teşekkürler.
