### ISSUE TITLE
Geliştirmeler

### ISSUE THREAD

**Issue by alvinaone** [metinorak/yordep#39]
Geliştirmeler devam ediyor mu? url rewrite gelmesi lazım mutlaka.

**Comment by metinorak** [comment]
Url rewrite derken entrylere url ekleme özelliğini kastediyorsanız o bulunuyor. Ama bunların butonlarını eklemedim henüz.

**Comment by metinorak** [comment]
Ha tamam anladım şimdi. Pek düşünmüyorum şu an onu.

**Comment by metinorak** [comment]
Şu an düşünmüyorum, bir ara ekleyebilirim.

**Comment by alvinaone** [comment]
bulsana beni ya lilcat34@gmail.com
