### ISSUE TITLE
Footer mesajı problemi 

### ISSUE THREAD

**Issue by fatihcirakk** [metinorak/yordep#6]
Sayfa boş oldugunda "Statistics" ve "telif hakkı" yazısı yukarda görünüyor, bu mesajın sürekli sayfanın altında sabit olması gerkemezmi?

**Comment by metinorak** [comment]
Sayfa altında sabit dediğimiz zaman olay çok başka birşey oluyor. Yani sürekli ekranda kalan bir yazı gibi. Bunun yerine minimum sayfa yüksekliği eklenebilir. Ama bu da yine çözünürlükten çözünürlüğe değişen bir durum. Benim kullandığım ekranın çözünürlüğünde aşağı dediğim kısım mesela 1000px'e denk geliyorsa başka bir ekranda 2000'e denk gelebilir. Yani yine pek düzgün bir çözüm gibi gözükmüyor gözüme.
